language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t marioleonel/docker-react -f Dockerfile.dev .    

script:
    - docker run -e CI=true marioleonel/docker-react npm run test -- --coverage